services:
  - type: web
    name: jobcompass
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY  
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false