[server]
port = 8501
address = "localhost"
headless = false
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "your-local-cookie-secret-change-this-in-production"

[auth.google]
client_id = "your-google-client-id"
client_secret = "your-google-client-secret"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[auth.github]
client_id = "your-github-client-id"
client_secret = "your-github-client-secret"
server_metadata_url = "https://token.actions.githubusercontent.com/.well-known/openid_configuration"

[theme]
# Primary accent color for interactive elements.
primaryColor = "#F63366"

# Background color for the main content area.
backgroundColor = "#fff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#fff"

# Color used for almost all text.
textColor = "#262730"
