[server]
port = 8501
address = "localhost"
headless = false
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

# Auth config moved to secrets.toml for security

[theme]
# Primary accent color for interactive elements.
primaryColor = "#F63366"

# Background color for the main content area.
backgroundColor = "#fff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#fff"

# Color used for almost all text.
textColor = "#262730"
